--- 
title: "Small Area Estimation Tools"
author: "UNFPA"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2: default
  bookdown::html_book: default
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  This eBook provides an introduction to the UNFPA small area estimation tools
link-citations: yes
github-repo: rstudio/bookdown-demo
site: bookdown::bookdown_site
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval=FALSE
)
```



# (PART) Introduction {-}

# Introduction

This document provides an introduction the the UNFPA small area estimation application.  Small area estimation is a statistical method often used to combine high-resolution census data with 
subject-specific but lower-resolution household surveys. This application provides a user-friendlty interface for conducting a small-area estimation analysis. It includes an interface for loading numerical censusand survey data, as well as shapefiles for display of results.  Users are directed to choose the relevant indicators from survey data, as well as variables that are common to both survey and census data as a basis for building a linear model. The application presents methods for checking the suitability of variables for modeling.  When the user has constructed a suitable model, the app allows for diagnostic testing of model results and finally prediction of the results into relevant census units. Users can export analytic steps as tabular or figure results.


